<!DOCTYPE html>
<html>

<?php include("common/design.php"); ?>
<?php include("common/casestudies_inc.php"); ?>

<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>OMNEST - Architecture Verification Case Studies</title>
    <meta name="robots" content="INDEX,FOLLOW" />
    <meta name="revisit-after" content="30" />
    <meta name="description" content="OMNEST Network Simulation Framework  - High-Performance Simulation for All Kinds of Networks" />
    <meta name="keywords" content="embeddable, discrete event simulator, simulation, c++, c, high-performance, open source, performance modeling, network simulation, protocol design, architecture verification, simulation framework, systemc, hla"  />
    <?php print_head_contribution(); ?>
    <script src="common/enlargeit.js" type="text/javascript"></script>
</head>

<body>
<?php print_leadin($product_menu, __FILE__); ?>

<div id="header"><h1>Case Study &ndash; Simulation of Next-Generation Supercomputing Systems at IBM Research</h1></div>

<p>Dr. Denzel and his colleagues at the IBM Zurich and Austin Research
Laboratories have built an OMNEST-based simulation framework that is
capable of simulating next-generation HPC (High-Performance Computing)
systems with hundreds of thousands of interconnected processors. Simulation
of such systems is indispensable for evaluating the system design options and
to help optimize the performance of the processors, the interconnection
network, and eventually the entire system, including software and HPC
applications.
</p>

<div class="pic right rounded">
<img src="images/misc/marenostrum-3.jpg" alt="The Mare Nostrum supercomputer" />
<div style="width:300px">The <i>Mare Nostrum</i> supercomputer, which has a unique
installation location, was optimized with the help of OMNEST (see text.)
It ranked #26 on the Top500 list of June 2008.
(<a href="http://www.treehugger.com/gadgets/how-to-treat-your-computer-marenostrum.html" target="_blank">source and more photos</a>)</div>
</div>

<p><i>"Large-scale end-to-end simulation of HPC systems running benchmark applications on
hundreds of thousands of processors communicating across a large interconnection network
is a challenge at the same level of detail as is required for system design and
development,"</i> they write.
The system, codenamed MARS, was built on an earlier, also OMNEST-based
simulation framework that they originally developed for switch and network
simulations in  telecom applications. This system allowed the
simulation of multistage fat-tree or mesh-type packet-switching
networks driven by statistical traffic.
</p>

<p>They extended this tool to support end-to-end coverage by replacing the
existing statistical packet generators with a new abstract computing node
model that is driven by real-world application traces. As the Message
Passing Interface (MPI) standard is pervasively used in HPC applications,
they used MPI traces to drive the model. These traces were collected from
applications of various fields: ocean modeling (HYCOM, POP), weather
research and forecast (WRF), shock-wave physics (CTH), and molecular
dynamics, fusion and transport physics (AMBER, CPMD, LAMMPS, GYRO, SPPM,
SWEEP3D, UMT2K). For another set of applications in the field of weather
forecast (DWD, ECMWF T639, ECMWF 4DVar), they used synthesized artificial
traces that were generated by application experts.
</p>

<div class="pic right">
<img src="images/misc/hpc-interconnect-example-thumb.png" alt="MARS simulator architecture" onclick="enlarge(this);" longdesc="images/misc/hpc-interconnect-example.png"/>
<div style="width:250px">Architecture of the OMNEST-based MARS simulator used for
optimizing high-performance computing systems (figure from the paper; click to enlarge)</div>
</div>

<p>The power of the framework was made possible in part by OMNEST facilities such as
parameterization. For example, the switch module could be configured into the
most popular switch architectures by parameterization. The size of the
switch, the number and arrangement of logical queues, buffer sizes, scheduling
options, the number of virtual circuits and priority classes, port speeds, and
the internal speedup and delays are examples of switch parameters.
</p>

<p>In simulations accompanying the development of new switches, it is frequently
necessary to add new functions or change existing functions. As they wrote,
<i>"[this was] flexibly possible because in OMNEST the lowest-level module
functions are programmed in C++."</i>
</p>

<p>For the simulation of larger HPC systems, the team exploited OMNEST's
parallel distributed simulation capability to speed up simulations and to
distribute memory requirements to multiple computers. A cluster of SMP
machines with the Parallel Operating Environment (POE) of the AIX&#0174; operating
system was used for parallel simulations. (The simulator can also be run on
x86 machines with either Linux or Windows operating system.)
</p>

<p>
Using the system, the team was able to choose the optimal interconnection
network (including the network topology, switch architecture and buffer sizes);
evaluate the trade-offs involving the use of indirect routes and adaptive routing;
perform GUPS (Giga Updates Per Second) benchmarks on the model;
and project the performance of selected existing MPI applications onto
the new future supercomputer system.
</p>

<p>In a follow-up paper, the team reports on how the MARS simulator was
used together with other tools to optimize the interconnection network at
the Mare Nostrum supercomputer of Barcelona Supercomputing Center (<a
href="http://www.top500.org/system/8242" target="_blank">Top500 link</a>).
The goal was to optimize the end-to-end performance with regard to actual
application programs running on the system. To accurately model the
applications, the team has collected application traces at the
message-passing interface level using an instrumentation package, and
connected the OMNEST-based network simulator MARS to an MPI task simulator
that replays the MPI traces. Both simulators generated output that can be
evaluated with a visualization tool. In the paper they also present several
examples of results obtained that provide insights that would not have been
possible without this integrated environment.
</p>


<p><a href="pdf/denzel2008.pdf">Read the full text (pdf)</a></p>

<p class="bibref">
Wolfgang E. Denzel (IBM Zurich Research Laboratory), Jian Li (IBM Austin Research Laboratory),
Peter Walker (Open Grid Computing Inc.) and Yuho Jin (Texas A&amp;M University), 2008.
<i>"A framework for end-to-end simulation of high-performance computing systems."</i>
Simutools '08: Proceedings of the 1st International Conference on Simulation
Tools and Techniques for Communications, Networks and Systems & Workshops: 1--10.
March 7, 2008, Marseille, France.
</p>

<p><a href="pdf/minkenberg2009.pdf">Follow-up paper (pdf)</a></p>

<p class="bibref">
Cyriel Minkenberg and German Rodriguez Herrera (IBM Zurich Research Laboratory), 2009.
<i>"Trace-driven Co-simulation of High-Performance Computing Systems using OMNeT++."</i>
OMNeT++ 2009: Proceedings of the 2nd International Workshop on OMNeT++ (hosted by SIMUTools 2009).
March 6, 2009, Rome, Italy.</p>

<?php print_next_casestudy_links(__FILE__); ?>

<?php print_leadout(); ?>
</body>
</html>

